project:
  type: website
  render:
    - index.qmd
    - bea_io.qmd
    # - bds.qmd
    # - qcew.qmd
  post-render: touch _site/.nojekyll

website:
  title: "pubdata"
  navbar:
    background: primary
    left:
      - text: Home
        href: index.qmd
      - text: BEA I-O
        href: bea_io.qmd
      # - text: BDS
      #   href: bds.qmd
      # - text: QCEW
      #   href: qcew.qmd

format:
  html:
    theme: cosmo
    toc: true



